version: '2'
services:
  web:
    # keopx/apache2-php available tags: latest, 7.0, 5.6.
    image: keopx/apache2-php:5.6
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
      - mail
    volumes:
      - ./data/www:/var/www # Data.
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./config/php/php.ini:/etc/php5/apache2/php.ini
      - ./config/php/xdebug.ini:/etc/php5/apache2/conf.d/20-xdebug.ini
      - ~/.ssh:/root/.ssh
    working_dir: /var/www
  # keopx/mysql available tags: latest, 5.7, 5.6, 5.5.
  mysql:
    image: keopx/mysql:5.5
    ports:
      - "3306:3306"
    volumes:
      - ./data/database:/var/lib/mysql
      #- ./config/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupaluser
      - MYSQL_PASSWORD=drupalpass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
  mail:
    image: mailhog/mailhog
    ports:
     - "8025:8025"